#+TITLE: Customs and Traditions
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: /Users/rajath/bleh/hugo/github-pages/blog
#+hugo_section: knowledge

- tags :: [[file:map_is_not_the_territory.org][Map is not the Territory]], [[file:mental_models.org][Mental Models]]

* Customs and Traditions
:PROPERTIES:
:ID:       6f318c64-9c36-4caa-8b0d-166e751b3c30
:END:
Every culture has customs and traditions that have been passed down to us from generation to generation. It's a way of doing things, sometimes a process, sometimes a workflow and it mostly has a specific context around it. Given that these span across generations and continue to be propagated in the name of customs/traditions, some of them lose their meaning along the way. They were created to either solve a specific problem or just as a better/easier way to do something. Once that meaning is lost and people start following the customs blindly, people somehow feel compelled to continue following those customs leading to [[file:continued_influence_effect.org][Continued Influence Effect]]

This is a case of [[file:map_is_not_the_territory.org][maps not being updated]] while the territories have changed completely. This also reminds me of "considering the cartographer" and "reality being the ultimate update".

* Example
There is an Indian tradition to kinda sprinkle water around the plate before we eat. Back in the day, food was eaten on the floor and the meals were on banana leaves rather than plates. The main reason for circling the plate with a ring of water was to keep ants away (since plates were on the floor). This is still followed now when we sit at the dining table and ants almost don't exist on the dining table. The map here is the ring of water around our plates and the territory /was/ to prevent ants from getting on to our plates. But this was still enforced while I was growing up for the sole reason that it's part of the tradition.

* Questions
- [[file:question.org][Question]]: Which other customs/traditions do I see being followed based on outdated information?
