#+title: How to take smart notes
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: /Users/rajath/bleh/hugo/github-pages/blog
#+hugo_section: knowledge

* Taking smart notes
- take *fleeting notes*. Have a single place where all your notes go. These notes won't be part of your zettelkasten. They go into trash
- review your fleeting notes the same day so that you don't forget the context in which you captured those notes
- make those notes part of your zettelkasten. These become *permanent notes*
- there's also *project notes* which are specific to a project. They can be archived once the project is complete. - I want to implement this, but not sure how to manage and keep it separate from the main set of notes.
- you should spend most of your time thinking and reflecting on what you learnt, not fiddling with the tools you use
- if you spend too much time customizing or configuring your tools, you are using the wrong tools
- select products that will be around forever - like text files
- while moving fleeting notes into permanent notes, ask yourself - "in which context will I want to stumble upon it again?"
- "the zettelkasten is designed to present you with ideas you've already forgotten, allowing your brain to focus on thinking instead of remembering"
- if you make permanent notes for everything you come across, then your zettelkasten gets diluted and good ideas don't surface up
