#+title: Map is not the Territory
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: /Users/rajath/bleh/hugo/github-pages/blog
#+hugo_section: knowledge

- tags :: [[file:mental_models.org][Mental Models]], [[file:learning.org][Learning]], [[file:book_the_great_mental_models_vol_1.org][Book: The Great Mental Models Vol.1]], [[file:books.org][Books]]
- source :: [[https://www.amazon.com/Great-Mental-Models-Thinking-Concepts-ebook/dp/B07P79P8ST][The Great Mental Models Vol. 1]]

* Notes
:PROPERTIES:
:ID:       751d4495-144d-4de6-a26c-ed6033467b1d
:END:
- Map is not a perfect depiction of the territory. If it was, it'll be the territory itself. Map is just a representation of the territory highlighting just certain aspects of it.
- We use maps everywhere from navigation to understanding a concept, customs, traditions, to even understanding reality itself. We use it so much that we sometimes forget to ask how it's relevant in today's day and age.
- Maps are useful since they are essentially a representation of reality and reality keeps changing, but most of the times maps stay the same. So, we get blindsided by following maps so diligently and forget that it may no longer apply. We may forget to update it, and just assume that we have all the answers.
- The other problem that we may run into is that we think maps are more important than territories - [[file:customs_and_traditions.org][Customs and Traditions]] would be a good example of this. And so is the [[file:slow_update_of_education_system.org][Slow update of Education System]].
- In order to use maps as a model as accurately as possible, we must remember 3 things:
  + reality is the ultimate update
  + consider the cartographer
  + maps can sometimes influence territories
* Questions
:PROPERTIES:
:ID:       2f66f4a5-ed48-4ee9-b347-ca5c8087be0d
:END:
- [[file:question.org][Question]]: Are there any (outdated) maps that I'm following for which the territories are already updated?
