#+TITLE: Second Order Thinking
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: /Users/rajath/bleh/hugo/github-pages/blog
#+hugo_section: knowledge

- tags :: [[file:mental_models.org][Mental Models]]
- source :: [[file:podcast_brain_lenses.org][Podcast: Brain Lenses]]

* Concept
- It's a concept where one not only thinks about the immediate consequences of an event, but also the secondary outcomes that are produced by the first outcomes
- This is hard because predicting primary outcomes is easy because there are very few unknowns. But predicting secondary outcomes is hard because of greater unknowns. Predicting tertiary outcomes are even harder because they posit on the guesswork on secondary outcomes.
* Example
A radical shift in car industry happens with 2 changes:
1. Electric vehicles
2. Autonomous vehicles
This would be the primary outcome.
Secondary outcome: convenience stores at gas stations will be affected because they no longer sell fuel, so people won't stop at those stores. People charge their cars either at home or at destination.
Tertiary outcome: items in those convenience stores will also change because cigarettes used to be the most common item that was being sold there.
* Questions
- [[file:question.org][Question]]: How to get better at Second Order Thinking?
  + One way I can think of is, while reading an article, pause for a moment after reading the headline to think about secondary or tertiary outcomes. Now compare what you thought with what is presented in the article. This may only work on long form articles that go in-depth in explaining one issue, not a mediocre news outlet with clickbait headlines that only tries to explain surface-level details.
- [[file:question.org][Question]]: You got the above example from a podcast episode. Think of another example.
