#+TITLE: Slow update of Education System
#+HUGO_AUTO_SET_LASTMOD: t
#+hugo_base_dir: /Users/rajath/bleh/hugo/github-pages/blog
#+hugo_section: knowledge

- tags :: [[file:map_is_not_the_territory.org][Map is not the Territory]], [[file:mental_models.org][Mental Models]]

* The Education System
Decades ago, the education system that we see today was created based on the job landscape that existed at the time. Then, with the dot com bubble and a boom in the IT industry, the job landscape changed drastically and technology moved really fast. Companies themselves were trying to keep up with newer languages and frameworks, they wanted the engineers they hired to be up to date with these technologies. Academia took a hit here since they were following the syllabus that was designed ages ago. The syllabus did get updated but not at the pace at which technologies changed.

This is the classic case of [[file:map_is_not_the_territory.org][Map not being the Territory]]. The education system that was created was a map of the job landscape (territory) among other things, of course. And that territory is not the same today.

There are many other flaws with the education system and this is just one aspect of it.

* Questions
- Are there any other slow update industries that are so mainly due to following their maps rigidly?
